name = "mlabs-haskell/uplc-benchmark"
version = "0.0.0"
license = "GPL-3.0-or-later"
description = "Aiken contracts for project 'mlabs-haskell/uplc-benchmark'"
compiler = "v1.0.29-alpha"

[repository]
user = "mlabs-haskell"
project = "uplc-benchmark"
platform = "github"

[[dependencies]]
name = "aiken-lang/stdlib"
version = "1.9.0"
source = "github"
